/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pourosova;

import java.awt.Image;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author mahadi
 */
public class deleteUser extends javax.swing.JFrame {

    /**
     * Creates new form deleteUser
     */
    public deleteUser() {
        setResizable(false);
        initComponents();
        logo();
        Nid();
        background();
    }

    public void background(){
        ImageIcon ic;
        ic=new ImageIcon("D:\\Java\\Pourosova\\Images\\back.jpg");
        Image im =ic.getImage();
        Image imscale =im.getScaledInstance(background.getWidth(),background.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon scaledicon = new ImageIcon(imscale);
        background.setIcon(scaledicon);
    }
    
    public void logo() {
        ImageIcon ic;
        ic = new ImageIcon("D:\\Java\\Pourosova\\Images\\logo.png");
        Image im = ic.getImage();
        Image imscale = im.getScaledInstance(logo.getWidth(), logo.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledicon = new ImageIcon(imscale);
        logo.setIcon(scaledicon);
    }

    public void Nid() {
        ImageIcon ic;
        ic = new ImageIcon("D:\\Java\\Pourosova\\Images\\nid.png");
        Image im = ic.getImage();
        Image imscale = im.getScaledInstance(nid_logo.getWidth(), nid_logo.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledicon = new ImageIcon(imscale);
        nid_logo.setIcon(scaledicon);
    }

    public void deleteUser() {
        try {
            // TODO add your handling code here:
            String Nid = nid.getText();

            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/rivendell_pourosova", "root", "admin");

            String query = "SELECT* FROM rivendell_pourosova.user_info WHERE NID='" + Nid + "';";
            PreparedStatement stm = con.prepareStatement(query);
            ResultSet r = stm.executeQuery(query);
            if (r.next()) 
            {
                String query1 = "DELETE FROM rivendell_pourosova.user_info WHERE NID='" + Nid + "';";
                // System.out.println(query);
                PreparedStatement stmt1 = con.prepareStatement(query1);
                stmt1.executeUpdate();
                JOptionPane.showMessageDialog(null, "Deleted");
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Wrong NID","Error",0);
                nid.setText("");
            }
        } catch (Exception ex) {
            //Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        nid = new javax.swing.JTextField();
        nid_logo = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JButton();
        back = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel1.setText("Insert the NID of the user to delete account");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 171, 369, 39));
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 43, 134, 94));

        nid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nidKeyPressed(evt);
            }
        });
        getContentPane().add(nid, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 228, 275, 40));
        getContentPane().add(nid_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 222, 59, 57));

        deleteBtn.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        getContentPane().add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 347, 88, 52));

        back.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 347, 91, 52));
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 460));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        deleteUser();
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        new Admin().setVisible(true);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void nidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nidKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            deleteUser();
        }
    }//GEN-LAST:event_nidKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(deleteUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(deleteUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(deleteUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(deleteUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new deleteUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel background;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField nid;
    private javax.swing.JLabel nid_logo;
    // End of variables declaration//GEN-END:variables
}
