/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pourosova;

import javax.swing.*;
import java.awt.Image;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import java.sql.*;
import java.util.regex.Pattern;

/**
 *
 * @author mahadi
 */
public class register extends javax.swing.JFrame {

    /**
     * Creates new form register
     */
    public register() {
        initComponents();
        setResizable(false);
        ScaleImage();
    }

    public void ScaleImage() {
        ImageIcon ic;
        ic = new ImageIcon("D:\\Java\\Pourosova\\Images\\back.jpg");
        Image im = ic.getImage();
        Image imscale = im.getScaledInstance(jLabel9.getWidth(), jLabel9.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledicon = new ImageIcon(imscale);
        jLabel9.setIcon(scaledicon);
    }

    public void resetBtnWork() {
        userName.setText(null);
        nid.setText(null);
        password.setText(null);
        rePassword.setText(null);
        email.setText(null);
        contact.setText(null);
    }

    public boolean contactVerification(String contact) {
        String contactFormate ="^(?:\\d{2}([-.])\\d{3}\\1\\d{3}\\1\\d{3}|\\d{11})$"; 
        Pattern p = Pattern.compile(contactFormate);
        if (contact == null || (contact.charAt(0)!='0' || contact.charAt(1)!='1')) {
            return false;
        }
        return p.matcher(contact).matches();
    }

    public boolean emailVerification(String email) {
        String emailFormate = "^[a-zA-Z0-9_!#$%&'*+/=?`{|}~^-]+(?:\\."
                + "[a-zA-Z0-9_!#$%&'*+/=?`{|}~^-]+)*@[a-zA-Z0-9-]+(?:\\.[a-zA-Z0-9-]+)*$";

        Pattern p = Pattern.compile(emailFormate);
        if (email == null) {
            return false;
        }
        return p.matcher(email).matches();
    }

    public void submitBtnWork() {
        try {
//             TODO add your handling code here:
            String username = userName.getText();
            String Nid = nid.getText();
            String pass = password.getText();
            String rePass = rePassword.getText();
            String Email = email.getText();
            String Contact = contact.getText();

            if ("".equals(username) || "".equals(Nid) || "".equals(pass) || "".equals(rePass) || "".equals(Email) || "".equals(Contact)) {
                JOptionPane.showMessageDialog(rootPane, "No field should be blank.", "Error", 0);
                return;
            }

            boolean ok = pass.equals(rePass);
            if (ok == false) {
                JOptionPane.showMessageDialog(rootPane, "Passwords aren't matched!", "Error", 0);
                password.setText(null);
                rePassword.setText(null);
            }

            if (emailVerification(Email) == false) {
                JOptionPane.showMessageDialog(rootPane, "Invalid Email.", "Error", 0);
                email.setText("");
                return;
            }

            if (contactVerification(Contact) == false) {
                JOptionPane.showMessageDialog(rootPane, "Invalid Contact.", "Error", 0);
                contact.setText("");
                return;
            }

            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/rivendell_pourosova", "root", "admin");

            String query = "INSERT INTO rivendell_pourosova.user_info(username,password,NID,email,contact) VALUES('" + username + "','" + pass + "','" + Nid + "','" + Email + "','" + Contact + "');";
//            System.out.println(query);
            PreparedStatement stmt = con.prepareStatement(query);
            stmt.executeUpdate(query);
            JOptionPane.showMessageDialog(rootPane, "Thank you for registration!", "Successful registration", 1);
            new UserMain().setVisible(true);
            dispose();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Sorry.\nThere already have an account with this NID.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        userName = new javax.swing.JTextField();
        nid = new javax.swing.JTextField();
        rePassword = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        submitBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        contact = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setMinimumSize(new java.awt.Dimension(700, 700));
        setPreferredSize(new java.awt.Dimension(800, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Java\\Pourosova\\Images\\username.png")); // NOI18N
        jLabel1.setToolTipText("User Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 88, 50, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\Java\\Pourosova\\Images\\nid.png")); // NOI18N
        jLabel2.setToolTipText("NID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 160, -1, 41));

        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\Java\\Pourosova\\Images\\password.png")); // NOI18N
        jLabel3.setToolTipText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 226, -1, 48));

        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\Java\\Pourosova\\Images\\password.png")); // NOI18N
        jLabel4.setToolTipText("Password (recheck)");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 300, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("D:\\Java\\Pourosova\\Images\\email.png")); // NOI18N
        jLabel5.setToolTipText("Email");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 376, 50, -1));
        getContentPane().add(userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 88, 402, 40));
        getContentPane().add(nid, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 161, 402, 40));
        getContentPane().add(rePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 310, 402, 40));

        password.setToolTipText("");
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 234, 402, 40));

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 384, 402, 40));

        jButton1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jButton1.setText("RESET");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 530, -1, 36));

        submitBtn.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        submitBtn.setText("SUBMIT");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(submitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 530, -1, 36));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jLabel6.setText("Please fill Up the form below to be registered");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 22, -1, 35));

        jLabel8.setIcon(new javax.swing.ImageIcon("D:\\Java\\Pourosova\\Images\\contact.png")); // NOI18N
        jLabel8.setToolTipText("Cell No.");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 50, 50));
        getContentPane().add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 452, 400, 40));

        jButton2.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, 80, 36));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        submitBtnWork();
    }//GEN-LAST:event_submitBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        resetBtnWork();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
//        if(emailVerification(email.getText())==false)
//        {
//            JOptionPane.showMessageDialog(rootPane, "Invaid","Error",0);
//        }
    }//GEN-LAST:event_emailActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new Welcome().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField contact;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nid;
    private javax.swing.JTextField password;
    private javax.swing.JTextField rePassword;
    private javax.swing.JButton submitBtn;
    private javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables
}
